import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./auth-provider";
import { Roboto } from "next/font/google"
import clsx from "clsx";

const robot = Roboto({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(robot.className, "h-screen text-gray-800")}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
